---
title: "Antiinfliacinės priemonės ir jų efektyvumas"
author: | 
  | Tomas Dzedulionis ir Dominykas Dzingelevičius
  | Vilniaus universitetas Ekonomikos ir verslo administravimo fakultetas
date: "01/06/2020"
output:
  pdf_document:
    fig_caption: yes
    fig_width: 6
    fig_height: 3
    number_sections: true
    toc: true 
    toc_depth: 3
    highlight: tango
    includes:
      in_header: header_lt_text.txt
bibliography: bibliography.bib
geometry: "left=3cm,right=3cm,top=2cm,bottom=2cm"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, warning = FALSE, message = FALSE)
if(!require("lubridate")) install.packages("lubridate"); library("lubridate") # for date conversion
if(!require("tidyverse")) install.packages("tidyverse"); library("tidyverse") # tidyr,dplyr,ggplot
if(!require("zoo")) install.packages("zoo"); library("zoo") # for date conversion
if(!require("reshape2")) install.packages("reshape2"); library("tidyverse") ## for data conversion
if(!require("gridExtra")) install.packages("gridExtra"); library("gridExtra") ## for grid.arrange
if(!require("data.table")) install.packages("data.table"); library("data.table") ## for data conversion
if(!require("eurostat")) install.packages("eurostat"); library("eurostat") ## for eurostat data import
if(!require("ggthemes")) install.packages("ggthemes"); library("ggthemes") ## ggplot themes
```

\newpage
# Įvadas

```{r,echo=FALSE,dev="pdf", dev.args=list(encoding="CP1257.enc"), fig.width=8, fig.height=5,fig.cap="Testuojam"}
exp <- get_eurostat("tet00003", filters=list(time="2019"))
exp <- exp%>% filter(geo%in%c("AT", "BE", "CY", "EE", "FI", "FR", "DE", "GR", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PT", "SK", "SI", "ES","BG", "HR", "CZ", "DK", "HU", "RO", "SE","EL","EU28"))%>%
        select(geo,values)%>%
        rename(export=values)
imp <- get_eurostat("tet00004", filters=list(time="2019"))
imp <- imp%>% filter(geo%in%c("AT", "BE", "CY", "EE", "FI", "FR", "DE", "GR", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PT", "SK", "SI", "ES","BG", "HR", "CZ", "DK", "HU","RO", "SE","EL","EU28"))%>%
        select(geo,values)%>%
        rename(import=values)
dfff <- merge(exp,imp)
dfff <- dfff%>%mutate(trade=import+export)%>%
        mutate_if(is.numeric, ~round(., 0))

ggplot(dfff, aes(x=reorder(geo, -trade),y=trade))+
        geom_bar(stat="identity", fill="steelblue")+
        theme_stata()+
        theme(axis.text.x=element_text(angle=45,hjust=1),
              axis.text=element_text(size=9),
              axis.title=element_text(size=12,face="bold"),
              plot.background = element_rect(fill = "white"))+
        labs(x="Valstybė", y="Ekonomikos atvirumas, %BVP", title="ES valstybių ekonomikų atvirumas 2019m.", 
             subtitle="Duomenų šaltinis: Eurostat")+
        geom_text(aes(label=paste0(trade,"")), vjust=-0.25, size=3)+
        theme(plot.title = element_text(hjust = 0),
              plot.subtitle = element_text(hjust = 0),axis.text=element_text(size=9))+
        scale_y_continuous(breaks=seq(0,450, by=100))
```